import NotFound from '../components/NotFound'
import PrivateRoute from '../components/PrivateRoute'
import Dashboard from '../users/Dashboard'
import Cart from '../users/Cart'
import Orders from '../users/Orders'
import Profile from '../users/Profile'
import Settings from '../users/Settings'
import Address from '../users/Address'
import Home from '../home/Home'
import Fashion from '../category/Fashion'
import Grocery from '../category/Grocery'
import Computers from '../category/Computers'
import Health from '../category/Health'
import Gaming from '../category/Gaming'
import Sports from '../category/Sports'
import Electronics from '../category/Electronics'
import Books from '../category/Books'

export {NotFound,PrivateRoute,Dashboard,Cart,Orders,Profile,Settings,Home,Address,Fashion,Grocery,Computers,Health,Gaming,Sports,Electronics,Books};