import NotFound from '../components/NotFound'
import PrivateRoute from '../components/PrivateRoute'
import Dashboard from '../users/Dashboard'
import Cart from '../users/Cart'
import Orders from '../users/Orders'
import Profile from '../users/Profile'
// import Settings from '../users/Settings'
import Home from '../home/Home'
import Fashion from '../category/Fashion'
import Grocery from '../category/Grocery'
import Computers from '../category/Computers'
import Health from '../category/Health'
import Gaming from '../category/Gaming'
import Sports from '../category/Sports'
import Electronics from '../category/Electronics'
import Books from '../category/Books'
import Settings from '../global/Settings'
import Voucher from '../global/Voucher'
import Services from '../global/Services'
import BesSellers from '../global/BestSellers'
import NewRelease from '../global/NewRelease'
import GiftIdea from '../global/GiftIdea'
import Dealoftheday from '../global/Dealoftheday'
import AllCategory from '../category/AllCategory'
import ItemPage from '../utils/ItemPage'
import SearchResult from '../Navbar/SearchResult'
import Address from '../users/Address'
export {NotFound,ItemPage,AllCategory,Address,PrivateRoute,Dashboard,Cart,Orders,Profile,Settings,Home,Fashion,Grocery,Computers,Health,Gaming,Sports,Electronics,Books,Voucher,Services,BesSellers,NewRelease,GiftIdea,Dealoftheday,SearchResult};